version: "3"
services:
  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - --prometheus_endpoint=/docker-metrics

  node-exporter:
    image: prom/node-exporter:v0.17.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    command:
      - --web.telemetry-path=/node-metrics
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)

  prometheus:
    image: prom/prometheus:v2.5.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
      - node-exporter

  grafana:
    # image: grafana/grafana:5.3.2
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    # environment:
    # - GF_AUTH_DISABLE_LOGIN_FORM=true
    # - GF_AUTH_ANONYMOUS_ENABLED=true
    # - GF_AUTH_ANONYMOUS_ORG_NAME=Admin
    # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  nginx:
    image: nginx:1.15.8
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/basic_auth:/etc/nginx/basic_auth
      - ./nginx/letsencrypt:/etc/letsencrypt/live
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana

volumes:
  grafana_data:
